import { useMemo } from 'react';
import { CheckCircle2, Lock, ShieldCheck, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useRiskStore } from '../store/riskStore';
import { DEMO_TRANSACTIONS } from '../data/demoTransactions';
import { calculateExpectedRtoExposure } from '../engine/exposureEngine';

export default function AdaptiveCheckout() {
  const { activeAnalysis, selectedTxId } = useRiskStore();
  const transaction = DEMO_TRANSACTIONS.find((item) => item.id === selectedTxId) || DEMO_TRANSACTIONS[0];
  const exposure = useMemo(() => activeAnalysis ? calculateExpectedRtoExposure(activeAnalysis.orderAmount, activeAnalysis.rtoProbability, (activeAnalysis.riskResult.intervention?.estimatedRiskImpact.projectedScore ?? activeAnalysis.riskScore) / 100) : null, [activeAnalysis]);
  const intervention = activeAnalysis?.riskResult.intervention;
  const customerMessage = intervention?.customerMessage || 'Complete your order securely with the payment method you prefer.';

  return <div className="mx-auto max-w-6xl space-y-6 pb-16 animate-slide-up">
    <header className="flex flex-col gap-3 border-b border-slate-200 pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-blue-600">Adaptive checkout</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">One decision, two experiences</h1><p className="mt-2 text-sm text-slate-500">Merchant controls stay private while the customer sees a clear, neutral next step.</p></div><span className="w-fit rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-700">Simulation mode</span></header>
    {!activeAnalysis ? <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><p className="text-sm font-semibold text-slate-900">Run a risk assessment to preview the adaptive checkout.</p><Link to="/checkout" className="mt-4 inline-flex rounded-lg bg-slate-900 px-4 py-2 text-xs font-semibold text-white">Open simulation</Link></div> : <>
      <div className="grid gap-5 lg:grid-cols-2">
        <section className="rounded-2xl border border-slate-200 bg-slate-950 p-6 text-white shadow-sm"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-blue-300">Merchant view</p><h2 className="mt-2 text-xl font-semibold">{transaction.orderNumber}</h2></div><ShieldCheck className="h-6 w-6 text-emerald-400" /></div><div className="mt-8 grid grid-cols-2 gap-4"><div><span className="text-xs text-slate-400">RTO probability</span><strong className="mt-1 block text-3xl font-bold tabular-nums">{Math.round(activeAnalysis.rtoProbability * 100)}%</strong></div><div><span className="text-xs text-slate-400">Recommended</span><strong className="mt-1 block text-sm text-emerald-300">{intervention?.title || activeAnalysis.decision.action.replaceAll('_', ' ')}</strong></div></div><div className="mt-6 border-t border-white/10 pt-4 text-sm leading-relaxed text-slate-300">{intervention?.merchantRationale || 'The selected policy remains active for this simulated transaction.'}</div>{exposure && <div className="mt-5 grid grid-cols-3 gap-3 text-xs"><div><span className="text-slate-500">Expected exposure</span><strong className="mt-1 block text-white">₹{Math.round(exposure.baselineExposure).toLocaleString('en-IN')}</strong></div><div><span className="text-slate-500">After intervention</span><strong className="mt-1 block text-emerald-300">₹{Math.round(exposure.projectedExposure ?? 0).toLocaleString('en-IN')}</strong></div><div><span className="text-slate-500">Potential reduction</span><strong className="mt-1 block text-emerald-300">₹{Math.round(exposure.potentialReduction ?? 0).toLocaleString('en-IN')}</strong></div></div>}</section>
        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 pb-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-blue-600">Customer view</p><h2 className="mt-2 text-xl font-semibold text-slate-900">Complete your order</h2></div><Lock className="h-5 w-5 text-slate-400" /></div><p className="mt-5 text-sm text-slate-600">{customerMessage}</p><div className="mt-6 space-y-3"><button className="flex w-full items-center justify-between rounded-xl border border-blue-200 bg-blue-50 p-4 text-left"><span><span className="block text-sm font-semibold text-slate-900">Verify your phone number</span><span className="mt-1 block text-xs text-slate-500">A quick confirmation keeps your order moving.</span></span><CheckCircle2 className="h-5 w-5 text-blue-600" /></button><button className="flex w-full items-center justify-between rounded-xl border border-slate-200 p-4 text-left"><span><span className="block text-sm font-semibold text-slate-900">Pay online</span><span className="mt-1 block text-xs text-slate-500">{intervention?.upiDiscount ? `Get ₹${intervention.upiDiscount} off your order.` : 'Fast confirmation with UPI or card.'}</span></span><Sparkles className="h-5 w-5 text-amber-500" /></button></div><p className="mt-6 text-center text-[11px] text-slate-400">{transaction.productName} · ₹{transaction.orderAmount.toLocaleString('en-IN')}</p></section>
      </div>
    </>}
  </div>;
}